### PR TITLE
Bonfire Ownership

### LINKED ISSUE #7: Bonfire ownership & breaking
Players that placed down a bonfire should be allowed to break it regardless of if there are players registered with it. The owner of a bonfire should be stored in the Bonfire table in the SQLite DB. 

Maybe also add some kind of message to the players that were registered with the bonfire after its broken that lets them know. Ideally this is also sent to offline players in some way, so that they get the message when they log in. Is this possible?

### PR DESCRIPTION
**Pull request by RuKira**
Added Bonfire Ownership
Removed ProtocolLib (unused)

Fixes #7

### CODE REVIEW

File: src/main/java/com/mineinabyss/bonfire/data/MessageQueue.kt [hunk 1]
```diff
@@ -0,0 +1,8 @@
+package com.mineinabyss.bonfire.data
+
+import org.jetbrains.exposed.dao.id.IntIdTable
+
+object MessageQueue : IntIdTable() {
+    val content = text("content")
```
Comment (Norazan) [inline src/main/java/com/mineinabyss/bonfire/data/MessageQueue.kt:6]: While this will work for now, storing queued messages in the database has the downside that we essentially can't retroactively change system messages after they have been stored in the queue. Players who haven't logged in in a while might still get the old message if we decide to change the message at any point. This is part of a larger problem though, with all our plugin messages to the player being hardcoded. I'd like them to eventually be stored somewhere else with unique identifiers to reference them. So ye thats for later, good for now!

File: src/main/java/com/mineinabyss/bonfire/listeners/BlockListener.kt [hunk 2]
```diff
@@ -95,12 +96,12 @@ object BlockListener : Listener {
 
         transaction {
             val hasRegisteredPlayers = Players.select { Players.bonfireUUID eq bonfire.uuid }.any()
+            val bonfireRow = Bonfire.select { Bonfire.entityUUID eq bonfire.uuid }.first()
```
Comment (Norazan) [inline src/main/java/com/mineinabyss/bonfire/listeners/BlockListener.kt:99]: There is a theoretical possibility (though it shouldn't happen) that the bonfire lacks a corresponding database entry. I always like to make sure that the plugin doesn't throw exceptions in that case, so you could do a `firstOrNull()` call. In this case that would mean that the `else { }` block below gets called, which is perfect.

File: src/main/java/com/mineinabyss/bonfire/listeners/PlayerListener.kt [hunk 3]
```diff
@@ -192,6 +195,13 @@ object PlayerListener : Listener {
                 }
             }
         }
+
+        transaction {
```
Comment (Norazan) [inline src/main/java/com/mineinabyss/bonfire/listeners/PlayerListener.kt]: Can include this code in the transaction above.

**Review by Norazan — CHANGES_REQUESTED** [review]
Looking real good! Just a few general cleanup comments here but I don't see any fundamental issues 👍 Just quickly fix these minor things and I'll merge.

File: src/main/java/com/mineinabyss/bonfire/listeners/PlayerListener.kt (hunk 3 above)
Comment (DevScyu) [reply src/main/java/com/mineinabyss/bonfire/listeners/PlayerListener.kt]: What about the ?: return@transaction

Comment (Norazan) [reply src/main/java/com/mineinabyss/bonfire/listeners/PlayerListener.kt]: oh ye, hm. could just change that to an if statement around the code below, with a null check. I'd prefer that than starting two separate transactions

Comment (RuKira) [reply src/main/java/com/mineinabyss/bonfire/listeners/PlayerListener.kt]: This is not possible.
At least from what Scyu and I tested.

File: src/main/java/com/mineinabyss/bonfire/listeners/BlockListener.kt (hunk 2 above)
Comment (RuKira) [reply src/main/java/com/mineinabyss/bonfire/listeners/BlockListener.kt]: This should be fixed now.

File: src/main/java/com/mineinabyss/bonfire/data/MessageQueue.kt (hunk 1 above)
Comment (RuKira) [reply src/main/java/com/mineinabyss/bonfire/data/MessageQueue.kt:6]: As per your request, I will ignore this "for now"

File: src/main/java/com/mineinabyss/bonfire/listeners/BlockListener.kt (hunk 2 above)
Comment (RuKira) [reply src/main/java/com/mineinabyss/bonfire/listeners/BlockListener.kt]: I would give this one last test, to ensure this is working.

**Review by Norazan — APPROVED** [review]
